### PR TITLE
Fix Authentication needed to access this field

### PR DESCRIPTION
**Pull request by dguyonvarch**
Add ticket fails with :
```
Could not reservate ticket.  
undefined  
Authentication needed to access this field
```

Just forget to add the `Bearer` keyword in the Authorisation header :wink:

### CODE REVIEW

**Comment by supa17** [comment]
hero , how do I apply this ?

**Comment by dguyonvarch** [comment]
> hero , how do I apply this ?

Clone my fork or wait for a new release with this PR

**Comment by supa17** [comment]
I copied and changed it with brackets. Does it automaticly update?

**Comment by supa17** [comment]
sorry i really dont have any experience with code haha

**Comment by dguyonvarch** [comment]
@supa17 So wait for a new release with this PR

**Comment by Ecostack** [comment]
I will check the PR in a bit!

**Pull request merged**
